# Generated by Django 4.2.23 on 2025-06-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TaskManager_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.AddField(
            model_name="task",
            name="categories",
            field=models.ManyToManyField(
                related_name="tasks", to="TaskManager_app.category"
            ),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="TaskManager_app.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
